# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"
a = s.split()
a

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

print ("The diameter of", planet,"is",diameter,"Kilometers" )



The diameter of Earth is 12742 Kilometers


In [ ]:
planet= "Earth"
diameter = 12742

print("The diameter of {} is {} Kilometers.".format(planet,diameter))

The diameter of Earth is 12742 Kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [ ]:
import numpy as np
a1=np.zeros(10)
a2=np.ones(10)*5
print(a1 , a2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
import numpy as np
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
import numpy as np
a=np.ones(10)*5
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [2]:
import numpy as np
a=np.arange(20,36)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
a=np.arange(0,9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c= np.concatenate((a,b))
print(c) 

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [4]:
import pandas 
import numpy 
a = numpy.random.randint(10, size=(3,2))
a1 = pandas.DataFrame(a)
a1


0  1
0  0  2
1  8  2
2  9  0

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [8]:
import pandas
import numpy
a = pandas.date_range(start='1-1-2023', end='10-2-2023',freq='D')
a

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [9]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [10]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
a = pd.DataFrame(lists)
a


0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24